// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGlxtw6L0ptMMvzmp0yO9OtVVxvMJ0mBc',
    appId: '1:784755401877:web:0509ceaa43b22ca7db679c',
    messagingSenderId: '784755401877',
    projectId: 'crud-5c255',
    authDomain: 'crud-5c255.firebaseapp.com',
    storageBucket: 'crud-5c255.appspot.com',
    measurementId: 'G-VYV39Y26FK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsMrziwjsT8V3DT9m3jcShsJFo_h8xlkU',
    appId: '1:784755401877:android:033cad09045808afdb679c',
    messagingSenderId: '784755401877',
    projectId: 'crud-5c255',
    storageBucket: 'crud-5c255.appspot.com',
  );
}
